In [3]:
import numpy as np
import pandas as pd

In [4]:
%pwd
%cd /Users/kabirmoghe/Documents/dreampath/backend

/Users/kabirmoghe/Documents/dreampath/backend

In [5]:
%load_ext autoreload
%autoreload 2

In [50]:
courses = pd.read_csv("dreampath_processing/courses/data/all_courses.csv")

In [51]:
courses[courses['course_code'].isna()]

Empty DataFrame
Columns: [course_title, course_url, course_code, description, prerequisites, degree_req, html_content, department, department_id, best_prereq_path]
Index: []

In [46]:
import json

DATA_DIR = "dreampath_processing/courses/data"
department_data = json.load(open(f"{DATA_DIR}/undergrad_department_links.json"))
dept_ids = json.load(open(f"{DATA_DIR}/undergrad_department_ids.json"))

In [47]:
from dreampath_processing.courses.data_retrieval.college_info_retrieval import produce_courses_for_department

department = "Mathematics"
department_id = dept_ids[department]

courses = produce_courses_for_department(department_data, department, department_id)

Navigating to: https://dartmouth.smartcatalogiq.com/current/orc/Departments-Programs-Undergraduate/Mathematics/MATH-Mathematics-Undergraduate
Department abbreviation: MATH
Found course: Timetable of Class Meetings
Found course: MATH 1 Introduction to Calculus
Found course: MATH 3 Calculus
Found course: MATH 4 Applications of Calculus to Medicine and Biology
Found course: MATH 5.01 Computational Text Analysis for the Social Sciences
Found course: MATH 5.04 Fundamental Applied Mathematics for the Sciences
Found course: MATH 7 First-Year Seminar in Mathematics
Found course: MATH 8 Calculus of Functions of One and Several Variables
Found course: MATH 9 Multivariable Differential Calculus with Linear Algebra
Found course: MATH 10 Introductory Statistics
Found course: MATH 11 Accelerated Multivariable Calculus
Found course: MATH 13 Calculus of Vector-Valued Functions
Found course: MATH 17 An Introduction to Mathematics Beyond Calculus
Found course: MATH 19 Introduction to Set Theory
Found course: MATH 20 Probability
Found course: MATH 22 Linear Algebra with Applications
Found course: MATH 23 Differential Equations
Found course: MATH 24 Linear Algebra
Found course: MATH 25 Number Theory
Found course: MATH 27 Dynamical Systems with Applicaitons
Found course: MATH 28 Introduction to Combinatorics
Found course: MATH 29 Introduction to Computability
Found course: MATH 30.04 Evolutionary Game Theory and Applications
Found course: MATH 31 Topics in Algebra
Found course: MATH 31.01 Topics in Algebra
Found course: MATH 32 The Shape of Space
Found course: MATH 35 Real Analysis
Found course: MATH 36 Mathematical Models in the Social Sciences
Found course: MATH 37 Computational methods in mathematical biology
Found course: MATH 38 Graph Theory
Found course: MATH 40 Probability and Statistical Inference
Found course: MATH 42 Differential Geometry I
Found course: MATH 43 Functions of a Complex Variable
Found course: MATH 46 Introduction to Applied Mathematics
Found course: MATH 47 Introduction to Mathematical Oncology
Found course: MATH 50 Introduction to Linear Models
Found course: MATH 53 Partial Differential Equations
Found course: MATH 54 Topology I
Found course: MATH 56 Computational Methods
Found course: MATH 60 Probability (Honors Section of MATH 20)
Found course: MATH 63 Real Analysis
Found course: MATH 66 Mathematical Topics in Modern Physics
Found course: MATH 68 Algebraic Combinatorics
Found course: MATH 69 Logic (Honors Section of MATH 39)
Found course: MATH 70 Elements of Multivariate Statistics & Statistical Learning
Found course: MATH 71 Algebra
Found course: MATH 72 Topics in Geometry
Found course: MATH 72.01 Calculus on Manifolds
Found course: MATH 72.02 Lie Groups: An Introduction Via Matrix Groups
Found course: MATH 72.10 Topics in Geometry
Found course: MATH 73 Metric Spaces and Measure Theory
Found course: MATH 74 Algebraic Topology
Found course: MATH 75 Mathematical Cryptography
Found course: MATH 75.01 Applied Topics in Number Theory and Algebra
Found course: MATH 76 Topics in Applied Mathematics
Found course: MATH 76.01 Topics in Applied Mathematics
Found course: MATH 76.02 Computational Inverse Problems
Found course: MATH 76.03 Evolutionary Dynamics
Found course: MATH 76.04 Modeling and Simulation of Living Systems
Found course: MATH 81 Abstract Algebra
Found course: MATH 86 Mathematical Finance I
Found course: MATH 87 Reading Course
Found course: MATH 89 Seminar in Logic
Found course: MATH 90 Data Intensive Research Project
Found course: MATH 96 Mathematical Finance II
Found course: MATH 97 Undergraduate Research
Found 66 courses for this link
Processing course 1/66: Timetable of Class Meetings
  No description found
Processing course 2/66: MATH 1 Introduction to Calculus
  Extracted description: This course is an introduction to single variable calculus for students who have not taken calculus ...
Processing course 3/66: MATH 3 Calculus
  Extracted description: This course is an introduction to single variable calculus aimed at students who have seen some calc...
Processing course 4/66: MATH 4 Applications of Calculus to Medicine and Biology
  Extracted description: This course will establish the relevance of calculus to medicine. It will develop mathematical tools...
Processing course 5/66: MATH 5.01 Computational Text Analysis for the Social Sciences
  Extracted description: Language is the medium for politics and political conflict. Candidates debate during elections. Repr...
Processing course 6/66: MATH 5.04 Fundamental Applied Mathematics for the Sciences
  Extracted description: Mathematics is the language of science. However, mathematics preparation for most science students t...
Processing course 7/66: MATH 7 First-Year Seminar in Mathematics
  No description found
Processing course 8/66: MATH 8 Calculus of Functions of One and Several Variables
  Extracted description: This course is a sequel to MATH 3 and is appropriate for students who have successfully completed an...
Processing course 9/66: MATH 9 Multivariable Differential Calculus with Linear Algebra
  Extracted description: This course includes the multivariable calculus material present in MATH 8 along with a brief introd...
Processing course 10/66: MATH 10 Introductory Statistics
  Extracted description: An introduction to the basic concepts of statistics. Topics include elementary probability theory, d...
Processing course 11/66: MATH 11 Accelerated Multivariable Calculus
  Extracted description: This briskly paced course can be viewed as equivalent to MATH 13 in terms of prerequisites, but is d...
Processing course 12/66: MATH 13 Calculus of Vector-Valued Functions
  Extracted description: This course is a sequel to MATH 8 and provides an introduction to calculus of vector-valued function...
Processing course 13/66: MATH 17 An Introduction to Mathematics Beyond Calculus
  Extracted description: Gives prospective Mathematics majors an early opportunity to delve into topics outside the standard ...
Processing course 14/66: MATH 19 Introduction to Set Theory
  Extracted description: This course introduces the axioms of set theory, the universe of sets, and set theory as a foundatio...
Processing course 15/66: MATH 20 Probability
  Extracted description: Our capacity to fathom the world around us hinges on our ability to understand quantities which are ...
Processing course 16/66: MATH 22 Linear Algebra with Applications
  Extracted description: This course presents the fundamental concepts and applications of linear algebra with emphasis on Eu...
Processing course 17/66: MATH 23 Differential Equations
  Extracted description: This course is a survey of important types of differential equations, both linear and non-linear. To...
Processing course 18/66: MATH 24 Linear Algebra
  Extracted description: This course is an introduction to the fundamental concepts of linear algebra in abstract vector spac...
Processing course 19/66: MATH 25 Number Theory
  Extracted description: The great mathematician C. F. Gauss once wrote "Mathematics is the queen of sciences and number theo...
Processing course 20/66: MATH 27 Dynamical Systems with Applicaitons
  Extracted description: Dynamical systems theory is the branch of mathematics that studies the properties of time-evolving p...
Processing course 21/66: MATH 28 Introduction to Combinatorics
  Extracted description: Beginning with techniques for counting-permutations and combinations, inclusion-exclusion, recursion...
Processing course 22/66: MATH 29 Introduction to Computability
  Extracted description: What does it mean for a function to be computable? This course examines several different mathematic...
Processing course 23/66: MATH 30.04 Evolutionary Game Theory and Applications
  Extracted description: Pioneered by John Maynard Smith and others, evolutionary game theory has become an important approac...
Processing course 24/66: MATH 31 Topics in Algebra
  Extracted description: This course will provide an introduction to fundamental algebraic structures, and may include signif...
Processing course 25/66: MATH 31.01 Topics in Algebra
  Extracted description: This course will provide an introduction to fundamental algebraic structures, and may include signif...
Processing course 26/66: MATH 32 The Shape of Space
  Extracted description: Topics in intuitive geometry and topology, for example: how to turn a sphere inside out; knots, link...
Processing course 27/66: MATH 35 Real Analysis
  Extracted description: This course introduces the basic concepts of real-variable theory. Topics include real numbers and c...
Processing course 28/66: MATH 36 Mathematical Models in the Social Sciences
  Extracted description: Disciplines such as anthropology, economics, sociology, psychology, and linguistics all now make ext...
Processing course 29/66: MATH 37 Computational methods in mathematical biology
  Extracted description: Introduction into cellular automata and agent-based modeling using the Java programming language. Fo...
Processing course 30/66: MATH 38 Graph Theory
  Extracted description: The theory of graphs has roots in both practical and recreational mathematics. Today there are major...
Processing course 31/66: MATH 40 Probability and Statistical Inference
  Extracted description: Introduction to continuous probability and statistical inference for data analysis. Includes the the...
Processing course 32/66: MATH 42 Differential Geometry I
  Extracted description: As the Greek roots of the word suggest, geometry has its origins in our natural and practical need t...
Processing course 33/66: MATH 43 Functions of a Complex Variable
  Extracted description: This course covers the differential and integral calculus of complex variables including such topics...
Processing course 34/66: MATH 46 Introduction to Applied Mathematics
  Extracted description: This course introduces a wide variety of mathematical tools and methods used to analyze phenomena in...
Processing course 35/66: MATH 47 Introduction to Mathematical Oncology
  Extracted description: Introduction into cancer biology and basic mathematical approaches to simulate cancer dynamics on th...
Processing course 36/66: MATH 50 Introduction to Linear Models
  Extracted description: This course provides an introduction to the most common model used in statistical data analysis. Sim...
Processing course 37/66: MATH 53 Partial Differential Equations
  Extracted description: Partial differential equations play critical roles in wide areas of mathematics, science, and engine...
Processing course 38/66: MATH 54 Topology I
  Extracted description: This course begins with the definitions of topological space, open sets, closed sets, neighborhoods,...
Processing course 39/66: MATH 56 Computational Methods
  Extracted description: This course introduces computational algorithms solving problems from a variety of scientific discip...
Processing course 40/66: MATH 60 Probability (Honors Section of MATH 20)
  Extracted description: This course is a more theoretical introduction to probability theory than MATH 20. In addition to th...
Processing course 41/66: MATH 63 Real Analysis
  Extracted description: This course introduces the basic concepts of real-variable theory. Topics include real numbers and c...
Processing course 42/66: MATH 66 Mathematical Topics in Modern Physics
  Extracted description: This introductory course presents mathematical topics that are relevant to issues in modern physics....
Processing course 43/66: MATH 68 Algebraic Combinatorics
  Extracted description: This course covers the use of abstract algebra in studying the existence, construction, enumeration,...
Processing course 44/66: MATH 69 Logic (Honors Section of MATH 39)
  Extracted description: This course begins with a study of relational systems as they occur in mathematics. First-order lang...
Processing course 45/66: MATH 70 Elements of Multivariate Statistics & Statistical Learning
  Extracted description: This course focuses on modern methods of statistical analysis including nonlinear models, data minin...
Processing course 46/66: MATH 71 Algebra
  Extracted description: The sequence MATH 71 and 81 is intended as an introduction to abstract algebra. MATH 71 develops bas...
Processing course 47/66: MATH 72 Topics in Geometry
  Extracted description: This course develops one or more topics in geometry. Possible topics include hyperbolic geometry; Ri...
Processing course 48/66: MATH 72.01 Calculus on Manifolds
  Extracted description: Manifolds provide mathematicians and other scientists with a way of grappling with the concept of “s...
Processing course 49/66: MATH 72.02 Lie Groups: An Introduction Via Matrix Groups
  Extracted description: Created by Sophus Lie (1842-1899) with the intent of developing a “Galois theory” of differential eq...
Processing course 50/66: MATH 72.10 Topics in Geometry
  Extracted description: This course develops one or more topics in geometry. Possible topics include ergodic theory & dynami...
Processing course 51/66: MATH 73 Metric Spaces and Measure Theory
  Extracted description: This course reviews the basic theory of metric spaces and their topology including continuity, compl...
Processing course 52/66: MATH 74 Algebraic Topology
  Extracted description: This course provides a foundation in algebraic topology, including both homotopy theory and homology...
Processing course 53/66: MATH 75 Mathematical Cryptography
  Extracted description: Cryptography is the science of secure communication over an insecure channel. This course focuses on...
Processing course 54/66: MATH 75.01 Applied Topics in Number Theory and Algebra
  Extracted description: Provides some applications of number theory and algebra. Specific topics will vary; two possibilitie...
Processing course 55/66: MATH 76 Topics in Applied Mathematics
  Extracted description: The numerical nature of twenty-first century society means that applied mathematics is everywhere: a...
Processing course 56/66: MATH 76.01 Topics in Applied Mathematics
  Extracted description: The numerical nature of twenty-first century society means that applied mathematics is everywhere: a...
Processing course 57/66: MATH 76.02 Computational Inverse Problems
  Extracted description: Inverse problems are ubiquitous in scientific research, and occur in applications ranging from medic...
Processing course 58/66: MATH 76.03 Evolutionary Dynamics
  Extracted description: Evolutionary dynamics is the mathematical study of evolutionary processes permeating every corner of...
Processing course 59/66: MATH 76.04 Modeling and Simulation of Living Systems
  Extracted description: Mathematical models play a key role in formulating null hypotheses for biological phenomenon and dev...
Processing course 60/66: MATH 81 Abstract Algebra
  Extracted description: This course provides a foundation in core areas in the theory of rings and fields. Specifically, it ...
Processing course 61/66: MATH 86 Mathematical Finance I
  Extracted description: Financial derivatives can be thought of as insurance against uncertain future financial events. This...
Processing course 62/66: MATH 87 Reading Course
  Extracted description: Advanced undergraduates occasionally arrange with a faculty member a reading course in a subject not...
Processing course 63/66: MATH 89 Seminar in Logic
  Extracted description: A study of selected topics in logic, such as model theory, set theory, recursive function theory, or...
Processing course 64/66: MATH 90 Data Intensive Research Project
  Extracted description: This course is intended for Mathematical Data Science majors as a means of satisfying their Culminat...
Processing course 65/66: MATH 96 Mathematical Finance II
  Extracted description: This course is a continuation of MATH 86 with an emphasis on the mathematics underlying fixed income...
Processing course 66/66: MATH 97 Undergraduate Research
  Extracted description: Open only to students who are officially registered in the Honors Program. Permission of the adviser...

In [49]:
courses[courses['course_code'].isna()]

Empty DataFrame
Columns: [course_title, course_url, course_code, description, prerequisites, degree_req, html_content, department, department_id]
Index: []

In [26]:
import pandas as pd
import json

for i in range(len(courses)):
    val = courses['best_prereq_path'].iloc[i]
    print(type(val))
    print(val)
    test = json.loads(val)

<class 'str'>
[]
<class 'str'>
[]
<class 'str'>
['COSC1']

JSONDecodeError: Expecting value: line 1 column 2 (char 1)

In [12]:
json.loads(courses['best_prereq_path'].iloc[0])

[]